---
dependencies:
  - ovirt_fluentd/read_local_ca_cert
  - ovirt_fluentd/ovirt_fluentd_package
  - { role: ovirt_fluentd/ovirt_host_packages, when: inventory_hostname in groups.hosts }
  - { role: ovirt_fluentd/ovirt_engine_packages, when: inventory_hostname in groups.engine }
  - ovirt_fluentd/fluentd_setup
  - ovirt_fluentd/set_fluentd_system_configurations
  - ovirt_fluentd/client
  - ovirt_fluentd/http_input
  - { role: ovirt_fluentd/ovirt_host, when: inventory_hostname in groups.hosts }
  - { role: ovirt_fluentd/ovirt_engine, when: inventory_hostname in groups.engine }
  - { role: ovirt_fluentd/ovirt_engine_logs, when: inventory_hostname in groups.engine }
  - ovirt_fluentd/ovirt_post_processing_common
