---
fluentd_engine_plugin_packages:
  - rubygem-fluent-plugin-collectd-nest
  - rubygem-fluent-plugin-rewrite-tag-filter
  - rubygem-fluent-plugin-secure-forward
  - rubygem-fluent-plugin-viaq_data_model
  - rubygem-fluent-plugin-elasticsearch
