---
ovirt_metrics_pkg_sysconf_dir: /etc/ovirt-engine-metrics

ovirt_metrics_config_yml_dir: "{{ ovirt_metrics_pkg_sysconf_dir }}/config.yml.d"

ovirt_metrics_config_yml_file: "{{ ovirt_metrics_pkg_sysconf_dir }}/config.yml"

# User that will own oVirt config.yml.d vars files.
ovirt_metrics_config_yml_d_owner: root

# Group that will own config.yml.d vars files.
ovirt_metrics_config_yml_d_group: root

# File mode for config.yml.d vars files.
ovirt_metrics_config_yml_d_mode: 0640

# File mode for config.yml.d vars directories.
ovirt_metrics_config_yml_d_dir_mode: 0750
