---
# Fluentd package name.
fluentd_package_name: fluentd

# A list of Fluentd plugins to install along with Fluentd.
fluentd_common_plugin_packages:
  - rubygem-fluent-plugin-collectd-nest
  - rubygem-fluent-plugin-rewrite-tag-filter
  - rubygem-fluent-plugin-secure-forward
  - rubygem-fluent-plugin-viaq_data_model
