---
- name: Configure processing for oVirt metrics
  when: ovirt_metrics_host_deploy is defined or inventory_hostname in groups.hosts
  block:
    - name: Set ovirt_vds_cluster_name fact
      ansible.builtin.set_fact:
        ovirt_vds_cluster_name: "{{ host_deploy_cluster_name }}"
      when: host_deploy_cluster_name is defined

    - name: Set ovirt_vds_vds_id fact
      ansible.builtin.set_fact:
        ovirt_vds_vds_id: unknown_id_{{ ansible_machine_id }}
      when: not ovirt_vds_vds_id is defined

    - name: Configure oVirt processing
      ansible.builtin.template:
        src: ovirt-processing.conf
        dest: '{{ fluentd_config_parts_dir }}/20-ovirt-processing.conf'
        owner: '{{ fluentd_owner }}'
        group: '{{ fluentd_group }}'
        mode: '{{ fluentd_config_mode }}'
      notify: Restart fluentd
