---
ovirt_engine_fqdn:

# Default output plugin

logging_output_type: elasticsearch

# Should the elasticsearch output include certificate to send HTTPS requests
use_omelasticsearch_cert: true

# User that will own logging config files.
logging_owner: root

# Group that will own logging config files.
logging_group: root

# File mode for logging configuration files.
logging_config_mode: "0640"

# The maximum supported message size (both for sending and receiving).
rsyslog_max_message_size: "64k"
